#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Function to run the external MiniSat solver
void run_miniSat(const char* filename) {
    char command[256];
    sprintf(command, "minisat %s result.txt", filename);  // Assuming 'minisat' is in the path
    system(command);

    // Read the result from the result.txt file generated by MiniSat
    FILE *result_file = fopen("result.txt", "r");
    if (!result_file) {
        perror("Failed to open result file");
        return;
    }

    char result[10];
    fgets(result, sizeof(result), result_file);
    if (strstr(result, "SATISFIABLE") != NULL) {
        printf("MiniSat: Satisfiable\n");
    } else {
        printf("MiniSat: Unsatisfiable\n");
    }
    fclose(result_file);
}
